// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: nesting/order.proto

package nesting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel     string        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	StoreId     string        `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	PhoneNumber string        `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Currency    string        `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Order       *OrderPayload `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	From        string        `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nesting_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_nesting_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_nesting_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Order) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *Order) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetOrder() *OrderPayload {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *Order) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrls   []string               `protobuf:"bytes,2,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Price       float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity    int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sku         string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Name        string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Category    string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Attributes  []string               `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nesting_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_nesting_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_nesting_order_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Item) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckoutRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Value:
	//
	//	*CheckoutRule_Delivery_
	//	*CheckoutRule_PaymentMethod_
	Value isCheckoutRule_Value `protobuf_oneof:"value"`
}

func (x *CheckoutRule) Reset() {
	*x = CheckoutRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nesting_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRule) ProtoMessage() {}

func (x *CheckoutRule) ProtoReflect() protoreflect.Message {
	mi := &file_nesting_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRule.ProtoReflect.Descriptor instead.
func (*CheckoutRule) Descriptor() ([]byte, []int) {
	return file_nesting_order_proto_rawDescGZIP(), []int{2}
}

func (x *CheckoutRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *CheckoutRule) GetValue() isCheckoutRule_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CheckoutRule) GetDelivery() *CheckoutRule_Delivery {
	if x, ok := x.GetValue().(*CheckoutRule_Delivery_); ok {
		return x.Delivery
	}
	return nil
}

func (x *CheckoutRule) GetPaymentMethod() *CheckoutRule_PaymentMethod {
	if x, ok := x.GetValue().(*CheckoutRule_PaymentMethod_); ok {
		return x.PaymentMethod
	}
	return nil
}

type isCheckoutRule_Value interface {
	isCheckoutRule_Value()
}

type CheckoutRule_Delivery_ struct {
	Delivery *CheckoutRule_Delivery `protobuf:"bytes,2,opt,name=delivery,proto3,oneof"`
}

type CheckoutRule_PaymentMethod_ struct {
	PaymentMethod *CheckoutRule_PaymentMethod `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3,oneof"`
}

func (*CheckoutRule_Delivery_) isCheckoutRule_Value() {}

func (*CheckoutRule_PaymentMethod_) isCheckoutRule_Value() {}

type OrderPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float32         `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`
	Sequence      int32           `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CheckoutRules []*CheckoutRule `protobuf:"bytes,4,rep,name=checkout_rules,json=checkoutRules,proto3" json:"checkout_rules,omitempty"`
	Status        string          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CustomerCode  string          `protobuf:"bytes,6,opt,name=customer_code,json=customerCode,proto3" json:"customer_code,omitempty"`
	Items         []*Item         `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *OrderPayload) Reset() {
	*x = OrderPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nesting_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayload) ProtoMessage() {}

func (x *OrderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_nesting_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayload.ProtoReflect.Descriptor instead.
func (*OrderPayload) Descriptor() ([]byte, []int) {
	return file_nesting_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderPayload) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderPayload) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrderPayload) GetCheckoutRules() []*CheckoutRule {
	if x != nil {
		return x.CheckoutRules
	}
	return nil
}

func (x *OrderPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderPayload) GetCustomerCode() string {
	if x != nil {
		return x.CustomerCode
	}
	return ""
}

func (x *OrderPayload) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckoutRule_Delivery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date   string  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CheckoutRule_Delivery) Reset() {
	*x = CheckoutRule_Delivery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nesting_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutRule_Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRule_Delivery) ProtoMessage() {}

func (x *CheckoutRule_Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_nesting_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRule_Delivery.ProtoReflect.Descriptor instead.
func (*CheckoutRule_Delivery) Descriptor() ([]byte, []int) {
	return file_nesting_order_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CheckoutRule_Delivery) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CheckoutRule_Delivery) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CheckoutRule_PaymentMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string  `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CheckoutRule_PaymentMethod) Reset() {
	*x = CheckoutRule_PaymentMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nesting_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutRule_PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRule_PaymentMethod) ProtoMessage() {}

func (x *CheckoutRule_PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_nesting_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRule_PaymentMethod.ProtoReflect.Descriptor instead.
func (*CheckoutRule_PaymentMethod) Descriptor() ([]byte, []int) {
	return file_nesting_order_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CheckoutRule_PaymentMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CheckoutRule_PaymentMethod) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_nesting_order_proto protoreflect.FileDescriptor

var file_nesting_order_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x6d, 0x70, 0x2e, 0x68, 0x79, 0x64, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a,
	0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x6d, 0x70, 0x2e,
	0x68, 0x79, 0x64, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0xe1, 0x02, 0x0a, 0x04, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x6b, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0xca, 0x02, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x49, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x59, 0x0a, 0x0e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x68, 0x79, 0x64, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x1a, 0x36, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a,
	0x3f, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8a, 0x02, 0x0a, 0x0c, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x68, 0x79, 0x64, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x16, 0x5a, 0x14, 0x74, 0x6d, 0x70, 0x2f, 0x68, 0x79,
	0x64, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nesting_order_proto_rawDescOnce sync.Once
	file_nesting_order_proto_rawDescData = file_nesting_order_proto_rawDesc
)

func file_nesting_order_proto_rawDescGZIP() []byte {
	file_nesting_order_proto_rawDescOnce.Do(func() {
		file_nesting_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_nesting_order_proto_rawDescData)
	})
	return file_nesting_order_proto_rawDescData
}

var file_nesting_order_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nesting_order_proto_goTypes = []interface{}{
	(*Order)(nil),                      // 0: tmp.hydrator.nesting.Order
	(*Item)(nil),                       // 1: tmp.hydrator.nesting.Item
	(*CheckoutRule)(nil),               // 2: tmp.hydrator.nesting.CheckoutRule
	(*OrderPayload)(nil),               // 3: tmp.hydrator.nesting.OrderPayload
	(*CheckoutRule_Delivery)(nil),      // 4: tmp.hydrator.nesting.CheckoutRule.Delivery
	(*CheckoutRule_PaymentMethod)(nil), // 5: tmp.hydrator.nesting.CheckoutRule.PaymentMethod
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_nesting_order_proto_depIdxs = []int32{
	3, // 0: tmp.hydrator.nesting.Order.order:type_name -> tmp.hydrator.nesting.OrderPayload
	6, // 1: tmp.hydrator.nesting.Item.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: tmp.hydrator.nesting.Item.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: tmp.hydrator.nesting.CheckoutRule.delivery:type_name -> tmp.hydrator.nesting.CheckoutRule.Delivery
	5, // 4: tmp.hydrator.nesting.CheckoutRule.payment_method:type_name -> tmp.hydrator.nesting.CheckoutRule.PaymentMethod
	2, // 5: tmp.hydrator.nesting.OrderPayload.checkout_rules:type_name -> tmp.hydrator.nesting.CheckoutRule
	1, // 6: tmp.hydrator.nesting.OrderPayload.items:type_name -> tmp.hydrator.nesting.Item
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nesting_order_proto_init() }
func file_nesting_order_proto_init() {
	if File_nesting_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nesting_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nesting_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nesting_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nesting_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nesting_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutRule_Delivery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nesting_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutRule_PaymentMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nesting_order_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CheckoutRule_Delivery_)(nil),
		(*CheckoutRule_PaymentMethod_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nesting_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nesting_order_proto_goTypes,
		DependencyIndexes: file_nesting_order_proto_depIdxs,
		MessageInfos:      file_nesting_order_proto_msgTypes,
	}.Build()
	File_nesting_order_proto = out.File
	file_nesting_order_proto_rawDesc = nil
	file_nesting_order_proto_goTypes = nil
	file_nesting_order_proto_depIdxs = nil
}
